import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

interface Prop {
  name: string;
  type: string;
  required: boolean;
  default: string | number | null;
  description: string;
}

interface Component {
  name: string;
  description: string;
  props: Prop[];
}

interface Guidance {
  variants: Array<{ variant: string; intent: string; typicalUse: string }>;
  rules: string[];
  states: Record<string, string>;
}

const root = fileURLToPath(new URL("..", import.meta.url));

// Read manifest and guidance
let components: Component[];
let guidance: Guidance;

try {
  components = JSON.parse(readFileSync(join(root, "dist/manifest.json"), "utf8")).components;
} catch {
  console.error("[react] ERROR: dist/manifest.json not found. Run `pnpm --filter @handamade/tokens build` and `pnpm --filter @handamade/react build` first.");
  process.exit(1);
}

try {
  guidance = JSON.parse(readFileSync(join(root, "../tokens/dist/guidance.json"), "utf8"));
} catch {
  console.error("[react] ERROR: ../tokens/dist/guidance.json not found. Run `pnpm --filter @handamade/tokens build` first.");
  process.exit(1);
}

// Escape and sanitize markdown table cells (collapse newlines and escape pipes)
function escapeCell(text: string | number | null): string {
  return String(text ?? "—")
    .replace(/\s*\n\s*/g, " ")
    .replace(/\|/g, "\\|");
}

// Convert camelCase to kebab-case
function toKebabCase(str: string): string {
  return str.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

mkdirSync(join(root, "docs"), { recursive: true });

for (const c of components) {
  // Build props table
  const props = c.props
    .map(
      (p) =>
        `| \`${escapeCell(p.name)}\` | \`${escapeCell(p.type)}\` | ${escapeCell(p.default)} | ${p.required ? "yes" : "no"} | ${escapeCell(p.description)} |`
    )
    .join("\n");

  // Determine token name (special cases where the component's PascalCase
  // name doesn't kebab-case to its actual --ds-{component}-* token prefix)
  const TOKEN_NAME_OVERRIDES: Record<string, string> = {
    IconButton: "button",
    NavBar: "navbar",
  };
  const tokenName = `--ds-${TOKEN_NAME_OVERRIDES[c.name] ?? toKebabCase(c.name)}-*`;

  // Check if component has variant prop
  const hasVariant = c.props.some((p) => p.name === "variant");

  // Build variant guidance section (only if component has variant prop)
  const variantGuidanceSection = hasVariant
    ? `## Variant guidance

${guidance.variants.map((v) => `- **${v.variant}** — ${v.intent}. ${v.typicalUse}.`).join("\n")}`
    : "";

  // Build rules section
  const rulesSection = `## Rules

${guidance.rules.map((r: string) => `- ${r}`).join("\n")}`;

  const md = `<!-- Generated by emit-docs.ts — do not edit. -->
# ${c.name}

${c.description}

## Props

| Prop | Type | Default | Required | Description |
|---|---|---|---|---|
${props}

## Theming

Override \`${tokenName}\` custom properties at any scope; interactive states derive automatically (${guidance.states.hover} hover, ${guidance.states.active} active).

${variantGuidanceSection}

${rulesSection}
`;

  writeFileSync(join(root, "docs", `${c.name}.md`), md);
}

console.log(`[react] wrote docs/*.md (${components.length})`);
