import type { ThemeDef } from "../src/dsl/types.js";

/**
 * Emit TypeScript type unions for token names, theme names, sizes, and variants.
 */
export function emitTokenTypes(
  themes: Record<string, ThemeDef>,
  sizes: number[] = [],
  variants: string[] = [],
  bps: Record<string, number> = {},
): string {
  // Collect all unique token names across themes
  const tokenNames = new Set<string>();
  for (const theme of Object.values(themes)) {
    for (const name of Object.keys(theme)) {
      tokenNames.add(name);
    }
  }

  const themeNames = Object.keys(themes);

  const lines: string[] = [];

  lines.push("// Auto-generated by @dku/tokens build script — do not edit");
  lines.push("");

  // TokenName union
  lines.push("export type TokenName =");
  const sortedTokens = [...tokenNames].sort();
  sortedTokens.forEach((name, i) => {
    const sep = i < sortedTokens.length - 1 ? "" : ";";
    lines.push(`  | "${name}"${sep}`);
  });
  lines.push("");

  // ThemeName union
  lines.push("export type ThemeName =");
  themeNames.forEach((name, i) => {
    const sep = i < themeNames.length - 1 ? "" : ";";
    lines.push(`  | "${name}"${sep}`);
  });
  lines.push("");

  // Size union (numbers unquoted)
  if (sizes.length > 0) {
    lines.push("export type Size =");
    sizes.forEach((size, i) => {
      const sep = i < sizes.length - 1 ? "" : ";";
      lines.push(`  | ${size}${sep}`);
    });
  } else {
    lines.push("export type Size = string;");
  }
  lines.push("");

  // Variant union
  if (variants.length > 0) {
    lines.push("export type Variant =");
    variants.forEach((name, i) => {
      const sep = i < variants.length - 1 ? "" : ";";
      lines.push(`  | "${name}"${sep}`);
    });
  } else {
    lines.push("export type Variant = string;");
  }
  lines.push("");

  // Breakpoints (D31) — literal constants, not a CSS-driven type
  if (Object.keys(bps).length > 0) {
    lines.push("export declare const breakpoints: {");
    for (const [k, v] of Object.entries(bps)) lines.push(`  readonly ${k}: ${v};`);
    lines.push("};");
    lines.push("");
  }

  return lines.join("\n");
}
