import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { ComponentEntry, PsiIndex } from "./types.js";
import { loadIndex } from "./index.js";

export const START_MARKER = "<!-- psi:agents:start -->";
export const END_MARKER = "<!-- psi:agents:end -->";

function axes(c: ComponentEntry): string {
  const type = (n: string) => c.props.find((p) => p.name === n)?.type;
  const parts: string[] = [];
  const variants = type("variant");
  const sizes = type("size");
  if (variants) parts.push(`variants: ${variants.replaceAll('"', "")}`);
  if (sizes) parts.push(`sizes: ${sizes}`);
  return parts.length ? ` — ${parts.join("; ")}` : "";
}

export function renderAgentsBlock(index: PsiIndex): string {
  return [
    START_MARKER,
    `# Psi (Ψ) design system — agent guide`,
    "",
    `Generated by \`npx @handamade/psi-mcp init\` for Psi v${index.version}. Re-run after upgrades; do not edit inside the markers (D44).`,
    "",
    "## House rules",
    "- Sizes are px numbers (24 | 32 | 40 | 48), never S/M/L.",
    "- Variants are flat: accent | accent-subtle | neutral | neutral-subtle | ghost | danger | danger-subtle | outline. One accent per visual group (Tags exempt, D40); danger only for destructive actions.",
    "- Never hardcode colors — bind var(--psi-*) custom properties.",
    "- Import all four token CSS files: base.css, one theme css, components.css, utilities.css (utilities is REQUIRED — .psi-container + reduced-motion zeroing).",
    `- Themes: ${index.themes.join(" | ")} — set data-psi-theme on <html> or a subtree root.`,
    "",
    `## Components (${index.components.length})`,
    ...index.components.map((c) => `- ${c.name}${axes(c)}`),
    "",
    "## Live documentation (MCP, tools: search/get)",
    "- Hosted: https://psi.kurkin.de/mcp (Streamable HTTP)",
    "- Local: `npx @handamade/psi-mcp` (stdio)",
    END_MARKER,
  ].join("\n");
}

export function applyBlock(existing: string | null, block: string): string {
  if (existing === null || existing.trim() === "") return block + "\n";
  if (existing.includes(START_MARKER) && existing.includes(END_MARKER)) {
    const re = new RegExp(`${START_MARKER}[\\s\\S]*?${END_MARKER}`);
    return existing.replace(re, () => block);
  }
  return existing.trimEnd() + "\n\n" + block + "\n";
}

export async function runInit(opts: { cwd: string; claude: boolean }): Promise<void> {
  const index = await loadIndex();
  const block = renderAgentsBlock(index);
  const files = ["AGENTS.md", ...(opts.claude ? ["CLAUDE.md"] : [])];
  for (const name of files) {
    const path = join(opts.cwd, name);
    const existing = existsSync(path) ? await readFile(path, "utf8") : null;
    await writeFile(path, applyBlock(existing, block));
    console.log(`${existing === null ? "created" : "updated"} ${name}`);
  }
}
